-- Add content generation status field to content table
-- This tracks when content assets are being generated by N8N workflows

ALTER TABLE content 
ADD COLUMN content_generation_status TEXT;

-- Add comment to explain the field
COMMENT ON COLUMN content.content_generation_status IS 'Tracks content asset generation status: generating, completed, failed, null (not generating)';

-- Add index for performance when querying by status
CREATE INDEX idx_content_generation_status ON content(content_generation_status); 