name: Deploy and Migrate

on:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Run Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          # Use Session Pooler URL format for CI/CD environments (supports IPv4/IPv6)
          # Format: postgres://postgres.PROJECT_ID:PASSWORD@aws-0-REGION.pooler.supabase.com:5432/postgres
          # We'll try common regions - adjust if your project is in a different region
          for region in "us-east-1" "us-west-2" "eu-west-1" "ap-southeast-1"; do
            DB_URL="postgres://postgres.${SUPABASE_PROJECT_ID}:${SUPABASE_DB_PASSWORD}@aws-0-${region}.pooler.supabase.com:5432/postgres"
            echo "Trying region: $region"
            if supabase db push --db-url "${DB_URL}" --dry-run; then
              echo "Found correct region: $region"
              supabase db push --db-url "${DB_URL}"
              exit 0
            fi
          done
          echo "Failed to connect with any region"
          exit 1 