name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
        
      - name: Run Migrations on Production
        env:
          PROD_SUPABASE_DB_URL: ${{ secrets.PROD_SUPABASE_DB_URL }}
        run: |
          echo "🚀 Running database migrations for production..."
          
          # Use direct connection with session mode to avoid prepared statement conflicts
          DIRECT_DB_URL=$(echo "$PROD_SUPABASE_DB_URL" | sed 's/\?.*$//')
          DIRECT_DB_URL="${DIRECT_DB_URL}?sslmode=require&pgbouncer=false"
          
          echo "⚡ Applying migrations with direct connection..."
          supabase db push --db-url "$DIRECT_DB_URL"
          
          echo "✅ Production database migrations completed!"

  deploy:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Deploy to Production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "🚀 Deploying to production..."
          
          # Deploy to production
          vercel --prod --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --confirm --force
          
          echo "✅ Production deployment completed!"
          echo "🌐 Available at: https://app3.transformo.io" 