name: Production Database Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
        
      - name: Run Migrations on Production
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          echo "🚀 Running database migrations for production..."
          supabase db push --db-url "$SUPABASE_DB_URL"
          echo "✅ Production database migrations completed!"
          echo "📋 Vercel will auto-deploy the app via Git integration" 