name: Staging Database Migration

on:
  push:
    branches:
      - staging

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: 1.200.3
        
      - name: Run Migrations on Staging
        env:
          STAGING_SUPABASE_DB_URL: ${{ secrets.STAGING_SUPABASE_DB_URL }}
        run: |
          echo "🚀 Running database migrations for staging..."
          
          # Apply migrations (skip dry-run to avoid prepared statement issues)
          echo "⚡ Applying migrations..."
          supabase db push --db-url "$STAGING_SUPABASE_DB_URL" --include-all
          
          echo "✅ Staging database migrations completed!"
          echo "📋 Vercel will auto-deploy the app via Git integration" 