name: Staging Database Migration

on:
  push:
    branches:
      - staging

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
        
      - name: Run Migrations on Staging
        env:
          SUPABASE_DB_URL: ${{ secrets.STAGING_SUPABASE_DB_URL }}
        run: |
          echo "🚀 Running database migrations for staging..."
          
          # Check if there are any pending migrations
          echo "📋 Checking migration status..."
          supabase db push --db-url "$SUPABASE_DB_URL" --dry-run || echo "No migrations to apply"
          
          # Apply migrations
          echo "⚡ Applying migrations..."
          supabase db push --db-url "$SUPABASE_DB_URL"
          
          echo "✅ Staging database migrations completed!"
          echo "📋 Vercel will auto-deploy the app via Git integration" 